name: Build and Run All Tests
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -O /tmp/rustup | sh /tmp/rustup -y
      - name: Install rust nightly
        run: rustup install nightly
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build using Cargo and Run All Tests
        run: cd {{github.workspace}} && cargo build && cargo test